[project]
name = "t2well-post"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib==3.3.4",
    "numpy==1.22.3",
    "openpyxl==3.1.2",
    "pandas==1.1.5",
    "xlwt==1.3.0",
]



[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.package-data]
"tough_well_post" = ["sample_files/*"]
